[user]
email = ""
password = ""

[files]
folder_path = "/home/bledy/Music/Red Hot Chili Peppers/Californication"
audio_format = ".flac"
excluded = [
    "album_info.txt",
]

[upload]
description = """
"""
thumbnail_url = "https://thumbs.spee.ch/view/4/86562ae3-125d-4cf6-8ca6-a2a83b7c2d78.jpg"
tags = [
    "music",
    "art",
    "flac",
    "rhcp",
    "red hot chili peppers",
]
channel = "@bLeDy"
deposit = 0.1
price = false
language = "en"
license_type = "copyright"
license_notice = "â„— 2020 bLeDy"
